# Generated by Django 3.2.7 on 2022-03-05 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallefactura',
            old_name='MovimientoInventario_producto',
            new_name='inventario_fijo',
        ),
        migrations.RenameField(
            model_name='detallefactura',
            old_name='subtotal',
            new_name='total_producto',
        ),
        migrations.RenameField(
            model_name='historicaldetallefactura',
            old_name='MovimientoInventario_producto',
            new_name='inventario_fijo',
        ),
        migrations.RenameField(
            model_name='historicaldetallefactura',
            old_name='subtotal',
            new_name='total_producto',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='MovimientoInventario',
        ),
        migrations.RemoveField(
            model_name='detallefactura',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='pedido',
        ),
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='MovimientoInventario',
        ),
        migrations.RemoveField(
            model_name='historicaldetallefactura',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='pedido',
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='cantidada',
            field=models.FloatField(default=0, help_text='Cantidad vendida'),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='inventario',
            field=models.ForeignKey(default=1, help_text='Inventario asociado', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.inventario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='lote',
            field=models.TextField(help_text='lote del producto', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='detallefactura',
            name='producto_fijo',
            field=models.TextField(default=1, help_text='producto asociado', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldetallefactura',
            name='cantidada',
            field=models.FloatField(default=0, help_text='Cantidad vendida'),
        ),
        migrations.AddField(
            model_name='historicaldetallefactura',
            name='inventario',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Inventario asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.inventario'),
        ),
        migrations.AddField(
            model_name='historicaldetallefactura',
            name='lote',
            field=models.TextField(help_text='lote del producto', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicaldetallefactura',
            name='producto_fijo',
            field=models.TextField(default=1, help_text='producto asociado', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detallefactura',
            name='producto',
            field=models.ForeignKey(help_text='detallepedido asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.producto'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='fecha_factura',
            field=models.DateTimeField(auto_now_add=True, help_text='fecha de generacion del pedido'),
        ),
        migrations.AlterField(
            model_name='historicaldetallefactura',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='detallepedido asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.producto'),
        ),
        migrations.AlterField(
            model_name='historicalfactura',
            name='fecha_factura',
            field=models.DateTimeField(blank=True, editable=False, help_text='fecha de generacion del pedido'),
        ),
    ]
