# Generated by Django 3.2.7 on 2022-03-29 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField(default=0, help_text='total de la nota')),
                ('descripcion', models.TextField(help_text='pequeña descripcion', max_length=150)),
                ('cliente', models.ForeignKey(help_text='cliente asociado', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.cliente')),
                ('instancia', models.ForeignKey(help_text='Instancia asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleNotasPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(default=0, help_text='monto a descontar')),
                ('instancia', models.ForeignKey(help_text='Instancia asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia')),
                ('notapago', models.ForeignKey(help_text='nota de pago asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.notaspago')),
                ('proforma', models.ForeignKey(help_text='proforma a la que afecta', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.proforma')),
            ],
        ),
    ]
