# Generated by Django 3.2.7 on 2022-02-10 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicallistaprecio',
            name='porcentaje',
            field=models.FloatField(default=0, help_text='Porcentaje de la lista de precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicallistaprecio',
            name='predeterminada',
            field=models.BooleanField(default=False, help_text='esta lista es la predeterminada?'),
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='porcentaje',
            field=models.FloatField(default=0, help_text='Porcentaje de la lista de precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='predeterminada',
            field=models.BooleanField(default=False, help_text='esta lista es la predeterminada?'),
        ),
        migrations.AlterField(
            model_name='historicalproducto',
            name='unidad',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, help_text='Unidad de medida del producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.unidad'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(default=None, help_text='Unidad de medida del producto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.unidad'),
        ),
    ]
