# Generated by Django 3.2.7 on 2022-03-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='precio_seleccionado',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='precio_seleccionado',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
