# Generated by Django 3.2.7 on 2022-03-02 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleproforma',
            name='MovimientoInventario_producto',
        ),
        migrations.RemoveField(
            model_name='historicaldetalleproforma',
            name='MovimientoInventario_producto',
        ),
        migrations.AddField(
            model_name='detalleproforma',
            name='cantidada',
            field=models.FloatField(default=0, help_text='Cantidad vendida'),
        ),
        migrations.AddField(
            model_name='detalleproforma',
            name='lista_precio',
            field=models.ForeignKey(default=1, help_text='Lista de precio asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.listaprecio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalleproforma',
            name='lote',
            field=models.TextField(help_text='lote del producto', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicaldetalleproforma',
            name='cantidada',
            field=models.FloatField(default=0, help_text='Cantidad vendida'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproforma',
            name='lista_precio',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Lista de precio asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.listaprecio'),
        ),
        migrations.AddField(
            model_name='historicaldetalleproforma',
            name='lote',
            field=models.TextField(help_text='lote del producto', max_length=150, null=True),
        ),
    ]
