# Generated by Django 3.2.7 on 2022-03-23 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220322_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproforma',
            name='precio_seleccionado',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldetalleproforma',
            name='precio_seleccionado',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
