# Generated by Django 3.2.7 on 2022-03-09 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220308_1514'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproducto',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='unidad',
        ),
    ]
