# Generated by Django 3.2.7 on 2022-02-16 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220210_1139'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='empresa',
            field=models.ForeignKey(default=1, help_text='empresa asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.empresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalcliente',
            name='empresa',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='empresa asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.empresa'),
        ),
    ]
