# Generated by Django 3.2.7 on 2022-03-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_detallenotaspago_notaspago'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproforma',
            name='saldo_proforma',
            field=models.FloatField(default=0, help_text='saldo pendiente de la proforma'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='saldo_proforma',
            field=models.FloatField(default=0, help_text='saldo pendiente de la proforma'),
        ),
    ]
