# Generated by Django 3.2.7 on 2022-01-28 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20220127_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmovimientoinventario',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento del producto', null=True),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento del producto', null=True),
        ),
    ]
