# Generated by Django 3.2.7 on 2022-02-02 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220128_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproducto',
            name='lote',
            field=models.BooleanField(default=False, help_text='¿Viene en lote?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='lote',
            field=models.BooleanField(default=False, help_text='¿Viene en lote?'),
        ),
    ]
