# Generated by Django 3.2.7 on 2022-03-02 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220302_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalproforma',
            name='monto_exento',
        ),
        migrations.RemoveField(
            model_name='historicalproforma',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='monto_exento',
        ),
        migrations.RemoveField(
            model_name='proforma',
            name='subtotal',
        ),
        migrations.AddField(
            model_name='historicalproforma',
            name='instancia',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Instancia asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.instancia'),
        ),
        migrations.AddField(
            model_name='proforma',
            name='instancia',
            field=models.ForeignKey(default=1, help_text='Instancia asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia'),
            preserve_default=False,
        ),
    ]
