# Generated by Django 3.2.7 on 2022-03-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20220309_1113'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidad',
            name='instancia',
        ),
        migrations.DeleteModel(
            name='HistoricalUnidad',
        ),
        migrations.DeleteModel(
            name='Unidad',
        ),
    ]
