# Generated by Django 3.2.7 on 2022-03-09 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220309_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventario',
            name='lote',
            field=models.TextField(default=1, help_text='Numero de lote del producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='lote',
            field=models.TextField(default='DDD001', help_text='Numero de lote del producto'),
            preserve_default=False,
        ),
    ]
