# Generated by Django 3.2.7 on 2022-02-18 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220216_1212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmovimientoinventario',
            name='cantida_disponible',
        ),
        migrations.RemoveField(
            model_name='movimientoinventario',
            name='cantida_disponible',
        ),
        migrations.AddField(
            model_name='historicalinventario',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento del producto', null=True),
        ),
        migrations.AddField(
            model_name='historicalinventario',
            name='lote',
            field=models.TextField(blank=True, help_text='Numero de lote del producto', null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='fecha_vencimiento',
            field=models.DateTimeField(blank=True, help_text='Fecha de vencimiento del producto', null=True),
        ),
        migrations.AddField(
            model_name='inventario',
            name='lote',
            field=models.TextField(blank=True, help_text='Numero de lote del producto', null=True),
        ),
    ]
