# Generated by Django 3.2.7 on 2022-03-02 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20220302_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleproforma',
            old_name='subtotal',
            new_name='total_producto',
        ),
        migrations.RenameField(
            model_name='historicaldetalleproforma',
            old_name='subtotal',
            new_name='total_producto',
        ),
    ]
