# Generated by Django 3.2.7 on 2022-03-09 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220309_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinventario',
            name='fecha_vencimiento',
            field=models.DateTimeField(default='2023-03-08T17:22:33-04:00', help_text='Fecha de vencimiento del producto'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inventario',
            name='fecha_vencimiento',
            field=models.DateTimeField(default='2023-03-08T17:22:33-04:00', help_text='Fecha de vencimiento del producto'),
            preserve_default=False,
        ),
    ]
