# Generated by Django 3.2.7 on 2022-03-02 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20220302_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleproforma',
            name='inventario',
            field=models.ForeignKey(help_text='Inventario asociado', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.inventario'),
        ),
        migrations.AlterField(
            model_name='historicaldetalleproforma',
            name='inventario',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Inventario asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.inventario'),
        ),
    ]
