# Generated by Django 3.2.7 on 2022-02-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20220221_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='total_producto',
            field=models.FloatField(default=0, help_text='total por producto'),
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='total_producto',
            field=models.FloatField(default=0, help_text='total por producto'),
        ),
        migrations.AlterField(
            model_name='historicalpedido',
            name='total',
            field=models.FloatField(default=0, help_text='total de la pedido'),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.FloatField(default=0, help_text='total de la pedido'),
        ),
    ]
