# Generated by Django 3.2.7 on 2022-02-23 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220221_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='lista_precio',
            field=models.ForeignKey(default=1, help_text='pedido asociado', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.listaprecio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='lista_precio',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='pedido asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.listaprecio'),
        ),
    ]
