# Generated by Django 3.2.7 on 2022-03-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20220311_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='correo_cliente',
            field=models.TextField(default='l', help_text='empresa asociada', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='correo_cliente',
            field=models.TextField(default='maiko', help_text='empresa asociada', max_length=150),
            preserve_default=False,
        ),
    ]
