# Generated by Django 3.2.7 on 2022-03-14 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20220314_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default=1, help_text='cliente asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='vendedor',
            field=models.ForeignKey(default=1, help_text='vendedor asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.vendedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='cliente',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='cliente asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.cliente'),
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='vendedor',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='vendedor asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.vendedor'),
        ),
    ]
