# Generated by Django 3.2.7 on 2022-02-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20220223_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='lote_producto',
            field=models.TextField(help_text='lote del producto', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='lote_producto',
            field=models.TextField(help_text='lote del producto', max_length=150, null=True),
        ),
    ]
