# Generated by Django 3.2.7 on 2022-02-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20220224_0919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detallepedido',
            old_name='cantidad',
            new_name='cantidada',
        ),
        migrations.RenameField(
            model_name='detallepedido',
            old_name='lote_producto',
            new_name='lote',
        ),
        migrations.RenameField(
            model_name='historicaldetallepedido',
            old_name='cantidad',
            new_name='cantidada',
        ),
        migrations.RenameField(
            model_name='historicaldetallepedido',
            old_name='lote_producto',
            new_name='lote',
        ),
    ]
