# Generated by Django 3.2.7 on 2022-03-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_auto_20220314_1147'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='factura',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='factura',
            name='vendedor',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='historicalfactura',
            name='vendedor',
        ),
        migrations.AddField(
            model_name='factura',
            name='id_cliente',
            field=models.TextField(default='l', help_text='Nombre del cliente en la venta', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='factura',
            name='id_vendedor',
            field=models.TextField(default='l', help_text='Nombre del cliente en la venta', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='id_cliente',
            field=models.TextField(default='l', help_text='Nombre del cliente en la venta', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalfactura',
            name='id_vendedor',
            field=models.TextField(default='l', help_text='Nombre del cliente en la venta', max_length=150),
            preserve_default=False,
        ),
    ]
