# Generated by Django 3.2.7 on 2022-02-24 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20220224_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallepedido',
            name='inventario',
            field=models.ForeignKey(default=6, help_text='Inventario asociado', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.inventario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldetallepedido',
            name='inventario',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Inventario asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.inventario'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='lista_precio',
            field=models.ForeignKey(help_text='Lista de precio asociada', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.listaprecio'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='pedido',
            field=models.ForeignKey(help_text='Pedido asociado', on_delete=django.db.models.deletion.DO_NOTHING, to='backend.pedido'),
        ),
        migrations.AlterField(
            model_name='detallepedido',
            name='producto',
            field=models.ForeignKey(help_text='Producto asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.producto'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='lista_precio',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Lista de precio asociada', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.listaprecio'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='pedido',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Pedido asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.pedido'),
        ),
        migrations.AlterField(
            model_name='historicaldetallepedido',
            name='producto',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Producto asociado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='backend.producto'),
        ),
    ]
