# Generated by Django 3.2.7 on 2022-03-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0010_auto_20220314_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='id_cliente',
            field=models.IntegerField(help_text='Nombre del cliente en la venta'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='id_vendedor',
            field=models.IntegerField(help_text='Nombre del cliente en la venta'),
        ),
        migrations.AlterField(
            model_name='historicalfactura',
            name='id_cliente',
            field=models.IntegerField(help_text='Nombre del cliente en la venta'),
        ),
        migrations.AlterField(
            model_name='historicalfactura',
            name='id_vendedor',
            field=models.IntegerField(help_text='Nombre del cliente en la venta'),
        ),
    ]
