# Generated by Django 3.2.7 on 2022-03-18 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_auto_20220314_1151'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaldetallelistaprecio',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaldetallelistaprecio',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='historicaldetallelistaprecio',
            name='listaprecio',
        ),
        migrations.RemoveField(
            model_name='historicaldetallelistaprecio',
            name='producto',
        ),
        migrations.RemoveField(
            model_name='historicallistaprecio',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicallistaprecio',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='listaprecio',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='detallepedido',
            name='lista_precio',
        ),
        migrations.RemoveField(
            model_name='detalleproforma',
            name='lista_precio',
        ),
        migrations.RemoveField(
            model_name='historicaldetallepedido',
            name='lista_precio',
        ),
        migrations.RemoveField(
            model_name='historicaldetalleproforma',
            name='lista_precio',
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='costo_2',
            field=models.FloatField(help_text='Costo del producto', null=True),
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='costo_3',
            field=models.FloatField(help_text='Costo del producto', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_2',
            field=models.FloatField(help_text='Costo del producto', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_3',
            field=models.FloatField(help_text='Costo del producto', null=True),
        ),
        migrations.DeleteModel(
            name='DetalleListaPrecio',
        ),
        migrations.DeleteModel(
            name='HistoricalDetalleListaPrecio',
        ),
        migrations.DeleteModel(
            name='HistoricalListaPrecio',
        ),
        migrations.DeleteModel(
            name='ListaPrecio',
        ),
    ]
