# Generated by Django 3.2.7 on 2022-05-18 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del nodo', max_length=120, null=True)),
                ('direccion_MAC', models.CharField(blank=True, help_text='MAC del nodo', max_length=20)),
                ('temperatura_min', models.FloatField(blank=True, null=True)),
                ('temperatura_max', models.FloatField(blank=True, null=True)),
                ('reenvio_correo', models.IntegerField(blank=True, default=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia')),
            ],
        ),
        migrations.CreateModel(
            name='Suscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.IntegerField(unique=True)),
                ('alertar', models.BooleanField(default=True)),
                ('instancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(help_text='Serial del sensor', max_length=120)),
                ('nombre', models.CharField(help_text='Nombre del sensor', max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia')),
                ('nodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tempro.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia')),
                ('nodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempro.nodo')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tempro.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='Puerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia')),
                ('nodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tempro.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField(max_length=254)),
                ('origen', models.TextField(max_length=254)),
                ('msg_mqtt', models.TextField(max_length=254)),
                ('nodo', models.CharField(blank=True, default='N/A', max_length=254, null=True)),
                ('sensor', models.CharField(blank=True, default='N/A', max_length=254, null=True)),
                ('estado', models.CharField(blank=True, default='N/A', max_length=254, null=True)),
                ('temperatura', models.CharField(blank=True, default='N/A', max_length=254, null=True)),
                ('contador', models.IntegerField(default=1)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia')),
            ],
        ),
        migrations.CreateModel(
            name='CorreoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('A', 'Alta'), ('B', 'Baja')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia')),
                ('nodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tempro.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(max_length=254)),
                ('nombre', models.CharField(help_text='Nombre del receptor', max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instancia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia')),
            ],
        ),
    ]
