# Generated by Django 3.2.7 on 2022-03-11 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Correo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.CharField(choices=[('1', 'Prioridad primera hora'), ('2', 'Prioridad segunda hora'), ('3', 'Prioridad tercera hora')], max_length=1, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('nombre', models.CharField(help_text='Nombre del receptor', max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del nodo', max_length=120, null=True)),
                ('MAC', models.CharField(help_text='MAC del nodo', max_length=20)),
                ('temperatura_min', models.IntegerField(blank=True, null=True)),
                ('temperatura_max', models.IntegerField(blank=True, null=True)),
                ('reenvio_correo', models.IntegerField(blank=True, default=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(help_text='Serial del sensor', max_length=120)),
                ('nombre', models.CharField(help_text='Nombre del sensor', max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Nodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tempro.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='Registro_temperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Nodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tempro.nodo')),
                ('Sensor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tempro.sensor')),
            ],
        ),
        migrations.CreateModel(
            name='PuertaEstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('A', 'Abierta'), ('C', 'Cerrada')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Nodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tempro.nodo')),
            ],
        ),
        migrations.CreateModel(
            name='Correo_alerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('A', 'Alta'), ('B', 'Baja')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('Nodo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tempro.nodo')),
            ],
        ),
    ]
