# Generated by Django 3.2.7 on 2022-03-21 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CorreoAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('A', 'Alta'), ('B', 'Baja')], max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroTemperatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperatura', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='PuertaEstatus',
            new_name='EstadoPuerta',
        ),
        migrations.RemoveField(
            model_name='registro_temperatura',
            name='Nodo',
        ),
        migrations.RemoveField(
            model_name='registro_temperatura',
            name='Sensor',
        ),
        migrations.RenameField(
            model_name='estadopuerta',
            old_name='estatus',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='nodo',
            old_name='MAC',
            new_name='direccion_MAC',
        ),
        migrations.DeleteModel(
            name='Correo_alerta',
        ),
        migrations.DeleteModel(
            name='Registro_temperatura',
        ),
        migrations.AddField(
            model_name='registrotemperatura',
            name='nodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tempro.nodo'),
        ),
        migrations.AddField(
            model_name='registrotemperatura',
            name='sensor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tempro.sensor'),
        ),
        migrations.AddField(
            model_name='correoalerta',
            name='nodo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='tempro.nodo'),
        ),
    ]
