# Generated by Django 3.2.7 on 2022-03-21 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tempro', '0002_auto_20220321_1507'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estadopuerta',
            old_name='Nodo',
            new_name='nodo',
        ),
        migrations.RenameField(
            model_name='sensor',
            old_name='Nodo',
            new_name='nodo',
        ),
        migrations.AlterField(
            model_name='correo',
            name='email',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='correo',
            name='nombre',
            field=models.CharField(help_text='Nombre del receptor', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='correo',
            name='prioridad',
            field=models.CharField(choices=[('1', 'Prioridad primera hora'), ('2', 'Prioridad segunda hora'), ('3', 'Prioridad tercera hora')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodo',
            name='direccion_MAC',
            field=models.CharField(blank=True, help_text='MAC del nodo', max_length=20),
        ),
        migrations.AlterField(
            model_name='nodo',
            name='temperatura_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='nodo',
            name='temperatura_min',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrotemperatura',
            name='nodo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tempro.nodo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrotemperatura',
            name='sensor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='tempro.sensor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registrotemperatura',
            name='temperatura',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
