# Generated by Django 3.2.7 on 2022-03-21 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempro', '0003_auto_20220321_1517'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EstadoPuerta',
            new_name='Puerta',
        ),
        migrations.RemoveField(
            model_name='correo',
            name='prioridad',
        ),
    ]
