# Generated by Django 3.2.7 on 2022-03-28 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        ('tempro', '0003_alter_suscripcion_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodo',
            name='instancia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia'),
            preserve_default=False,
        ),
    ]
