# Generated by Django 3.2.7 on 2022-03-22 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempro', '0004_auto_20220321_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon', models.TextField(max_length=254)),
                ('origen', models.TextField(max_length=254)),
                ('msg_mqtt', models.TextField(max_length=254)),
                ('nodo', models.CharField(blank=True, max_length=254, null=True)),
                ('sensor', models.CharField(blank=True, max_length=254, null=True)),
                ('estado', models.CharField(blank=True, max_length=254, null=True)),
                ('temperatura', models.CharField(blank=True, max_length=254, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
