# Generated by Django 3.2.7 on 2022-03-28 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        ('tempro', '0004_nodo_instancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='instancia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='correoalerta',
            name='instancia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='error',
            name='instancia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='puerta',
            name='instancia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registrotemperatura',
            name='instancia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sensor',
            name='instancia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='instancia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='backend.instancia'),
            preserve_default=False,
        ),
    ]
