# Generated by Django 3.2.7 on 2022-03-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempro', '0005_error'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='estado',
            field=models.CharField(blank=True, default='N/A', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='nodo',
            field=models.CharField(blank=True, default='N/A', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='sensor',
            field=models.CharField(blank=True, default='N/A', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='error',
            name='temperatura',
            field=models.CharField(blank=True, default='N/A', max_length=254, null=True),
        ),
    ]
