# Generated by Django 3.2.7 on 2022-03-22 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tempro', '0006_auto_20220322_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='contador',
            field=models.IntegerField(default=1),
        ),
    ]
