# Generated by Django 3.2.7 on 2022-03-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tempro', '0006_alter_suscripcion_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correo',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='correoalerta',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='error',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='nodo',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='puerta',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='registrotemperatura',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='sensor',
            name='instancia',
        ),
        migrations.RemoveField(
            model_name='suscripcion',
            name='instancia',
        ),
    ]
