# Generated by Django 3.2.7 on 2022-03-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        ('tempro', '0007_auto_20220328_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='correo',
            name='instancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia'),
        ),
        migrations.AddField(
            model_name='correoalerta',
            name='instancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia'),
        ),
        migrations.AddField(
            model_name='error',
            name='instancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia'),
        ),
        migrations.AddField(
            model_name='nodo',
            name='instancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia'),
        ),
        migrations.AddField(
            model_name='puerta',
            name='instancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia'),
        ),
        migrations.AddField(
            model_name='registrotemperatura',
            name='instancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='instancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia'),
        ),
        migrations.AddField(
            model_name='suscripcion',
            name='instancia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='backend.instancia'),
        ),
    ]
